#!/bin/bash
# Gera .env de produção com secrets criptograficamente seguros
# Uso: bash scripts/gerar-env-producao.sh > .env
#
# ATENÇÃO: o arquivo gerado contém credenciais reais.
# - Nunca commite o .env no git.
# - Armazene em local seguro (ex.: Bitwarden, AWS Secrets Manager).

set -euo pipefail

echo "# ============================================"
echo "# .env de PRODUCAO — Global Engenharia OS"
echo "# Gerado em: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# NAO commitar este arquivo no git!"
echo "# ============================================"
echo ""
echo "NODE_ENV=production"
echo "PORT=3333"
echo "HOST=0.0.0.0"
echo ""
echo "# Banco de dados"
POSTGRES_PASS="$(openssl rand -base64 32 | tr -d '/+=')"
echo "DATABASE_URL=postgresql://gestor:${POSTGRES_PASS}@postgres:5432/os_global?schema=public&connection_limit=10&pool_timeout=20"
echo "POSTGRES_USER=gestor"
echo "POSTGRES_PASSWORD=${POSTGRES_PASS}"
echo "POSTGRES_DB=os_global"
echo ""
echo "# Redis"
REDIS_PASS="$(openssl rand -base64 24 | tr -d '/+=')"
echo "REDIS_URL=redis://:${REDIS_PASS}@redis:6379"
echo "REDIS_PASSWORD=${REDIS_PASS}"
echo ""
echo "# JWT (minimo 256 bits)"
echo "JWT_SECRET=$(openssl rand -base64 48)"
echo "JWT_REFRESH_SECRET=$(openssl rand -base64 48)"
echo "JWT_EXPIRES_IN=15m"
echo "JWT_REFRESH_EXPIRES_IN=7d"
echo ""
echo "# Dominio (preencher manualmente)"
echo "FRONTEND_URL=https://app.seudominio.com.br"
echo "API_URL=https://api.seudominio.com.br"
echo ""
echo "# WhatsApp Meta (preencher manualmente)"
echo "META_WHATSAPP_TOKEN="
echo "META_PHONE_NUMBER_ID="
echo "META_VERIFY_TOKEN=$(openssl rand -hex 20)"
echo "META_APP_SECRET="
echo ""
echo "# Admin inicial (trocar apos primeiro login)"
echo "ADMIN_SEED_EMAIL=admin@globalengenharia.com.br"
echo "ADMIN_SEED_SENHA=$(openssl rand -base64 16 | tr -d '/+=')"
echo ""
echo "# Storage"
echo "STORAGE_DIR=/app/storage"
echo ""
echo "# Google Calendar (opcional)"
echo "GOOGLE_CALENDAR_ENABLED=false"
echo "GOOGLE_SERVICE_ACCOUNT_JSON="
echo ""
echo "# MercadoPago (opcional)"
echo "MERCADOPAGO_ACCESS_TOKEN="
echo "MERCADOPAGO_WEBHOOK_SECRET=$(openssl rand -hex 32)"
